### ISSUE TITLE
Taking screenshots of an area doesn't work via keyboard shortcut

### ISSUE THREAD

**Issue by silviucc** [mate-desktop/mate-utils#37]
I'm trying to create a custom keyboard shortcut that invokes mate-screenshot with the option to select only an area of the screen. This should mean invoking the command with the -a or --area switch but it only works in a terminal. If I try to create the keyboard shortcut it always takes a screenshot of the whole screen. Does not allow me to select any area.

The workaround was to use the -i option which allows me to select what I want to do, but still, it looks like a bug.

Using Mate 1.6 on Manjaro 64bit.
##

**Comment by monsta** [comment]
Does it still happen in 1.10?

**Comment by martin-bts** [comment]
@monsta: yes, it does

**Comment by martin-bts** [comment]
It's a timing issue! 
I created a /usr/local/bin/mate-screenshot which looks like this:

    #!/bin/bash
    sleep 1
    exec /usr/bin/mate-screenshot $@

If I point my shortcut towards this script instead of the binary, it works. Notice that I still provide the `-a` parameter as part of the shortcut definition.

**Comment by monsta** [comment]
Ok, confirmed. Interesting that a panel launcher with ```mate-screenshot -a``` works just fine.

**Comment by aug-riedinger** [comment]
Thanks @martin-bts for workaround. Works very well, even with `sleep 0.1`, which feels like nothing.

A fix would be great though!

**Comment by monsta** [comment]
We'll try to fix it of course, I just can't make any promises about the date... our team is quite small and our [issues list](https://github.com/issues?user=mate-desktop) is growing every day. Pull requests with fixes are welcome, as usual.

**Comment by aug-riedinger** [comment]
I guess, no criticism in my comment of course.

I wish I could help, but C kind of scares me...

Any tip on where to look at in the code? I checked https://github.com/mate-desktop/mate-utils/blob/master/mate-screenshot/src/mate-screenshot.c but it is such a long file I got easily lost.

Finally, if this is a fork from gnome-screenshot, does the fix needs to be accepted in both repositories to be released?

**Comment by monsta** [comment]
I'm not sure where to look yet... and maybe it's already fixed in gnome, not sure about this as well.

**Comment by davidforgianni** [comment]
I installed krita and shutter first.  Then to Shutter preferences>Actions: open with Krita (for editing). Then set the dconf keybinding-command to 'shutter -s'.  Works pretty good, although i would like to not have the Shutter application window open after capturing, just open in Krita.  If i find how to do that I will update this post, I hope this helps, thank you!

`sudo add-apt-repository ppa:kubuntu-ppa/backports; sudo apt-get update; sudo apt-get install krita
sudo add-apt-repository ppa:shutter/ppasudo add-apt-repository ppa:shutter/ppa; sudo apt-get update; sudo apt-get install shutter`

![selection_004](https://cloud.githubusercontent.com/assets/4622642/14303037/95acd174-fb6c-11e5-8160-7f20e31b1f22.png)

**Comment by huangjj27** [comment]
Nowaday the bug still exists with mate-utils 1.12 on ubuntu-mate 16.04. Please fix it soon!

**Comment by RadW2020** [comment]
![screenshot at 2016-08-01 13 06 15](https://cloud.githubusercontent.com/assets/8538542/17292223/da78323e-57e8-11e6-9671-231cb962e3a4.png)

Still happening.

**Comment by N0rbert** [comment]
I reported this to launchpad as [bug 1615748](https://bugs.launchpad.net/bugs/1615748) on Ubuntu 16.04.

**Comment by bitshark** [comment]
This continues to happen on Void Linux latest with Mate 1.14.1.  Interestingly, it also happens (identical problem) with gnome-screenshot.

Keyboard shortcuts to either 'mate-screenshot --interactive' or 'mate-screenshot --window' work fine, but mate-screenshot --area does not work.

**Comment by bitshark** [comment]
I just did some analysis of the problem -- here's what I found.

1. I was able to use the workaround suggested by martin-bts.  I created the following script, and called this script instead of calling mate-screenshot from the keyboard shortcut.

I noticed that the timing issue is subtle... If I sleep for 30ms prior to calling mate-screenshot, the command will not work.  If I sleep for 40ms prior to calling mate-screenshot, the command WILL work.

`[user@dolphin ~]$ cat /usr/local/bin/my-screenshot 
#!/bin/bash
sleep 0.04	# this works... 40ms is long enough
#0.01 - no	# this does not, 10ms is not long enough
#0.03 - no	# this does not work, 30ms is not long enough
#0.04 - yes	# etc
#0.05 - yes
/usr/bin/mate-screenshot --area
`

2. I was curious as to what was going on with this, so I conducted an strace of the process call (mate-screenshot --area)  under a condition where it succeeded (sleep 40ms)  vs where it failed (sleep 10ms).

What I found were the following differences:
- The success vs failed runs resulted in mate-screenshot reading and writing different bytes to two files
- One of these files is ~/.Xauthority (fd = 4) in the strace.
- The other file is ~/.config/dconf/user , which had differences in two places.

I'm not that familiar with dconf so I can't really take this further, but I hope this helps resolve the problem.

This screenshot shows that the fd=4 file descriptor is ~/.Xauthority
![mate-screenshot-xauthority](https://cloud.githubusercontent.com/assets/5384760/19172457/cb5b66fa-8bd6-11e6-9505-ceae5bfdae17.png)

This screenshot shows the first difference between the straces, in regard to read/write of both ~/.Xauthority and ~/.config/dconf/user

![matescreenshot_strace_diff1](https://cloud.githubusercontent.com/assets/5384760/19172478/ec10f0ae-8bd6-11e6-80e5-96632f80a17f.png)

This is the second difference between the straces.  They are identical besides what is displayed in these images.
![mate-screenshot-strace-diff2](https://cloud.githubusercontent.com/assets/5384760/19172497/038a54a0-8bd7-11e6-91cb-ba89f51bf930.png)

I also did a diff of the ~/.config/dconf/user file under both success and failure conditions (since mate-screenshot is read/writing this file).  I found some differences , but I don't know how to interpret them and whether they are material.

First difference between working ~/.config/dconf/user and non-working 
![mate-screenshot-dconf-diff1](https://cloud.githubusercontent.com/assets/5384760/19172541/3cc86ea0-8bd7-11e6-9b3f-d50a45e675c5.png)

Second difference between working ~/.config/dconf/user and non-working
![mate-screenshot-dconf-diff2](https://cloud.githubusercontent.com/assets/5384760/19172548/48bc3034-8bd7-11e6-8539-e051fef1ac28.png)


Anyway I hope this helps.  In the meantime, you can use the workaround detailed above and create a wrapper script that sleeps for 50 to 100ms prior to calling mate-screenshot --area

**Comment by rsmith31415** [comment]
Still an issue in Mate Desktop Environment 1.16 on Ubuntu Mate 16.10, but @martin-bts' solution is a good workaround.

**Comment by N0rbert** [comment]
Got this bug again on fresh installation of Ubuntu MATE 16.04.3 LTS.
I reported this [bug 1615748](https://bugs.launchpad.net/mate-desktop/+bug/1615748) on Launchpad previously, now I linking it here.
What is interesting: if I add ` -i` to `mate-screenshot -a` it works as expected (but opens interactive window).

**Comment by raveit65** [comment]
Surprise surprise.
With 1.18.2 (un patched) in fedora25/26 and using <mod4>+ a i have to press the **a** several times than it works with 'mate-screenshot -a' :-)
.... mod4= super key

**Comment by raveit65** [comment]
It works also i hold the **a** key a bit longer, but than it is possible that abrt (bug reporting tool) pops up and i have a stacktrace.
But the stacktrace starts with malloc.c and nvidia.
So this isn't helpful.

**Comment by andreamoro** [comment]
I've been reading tons of post complaining about this all over the places. I'm a newbie myself on linux mint, but I've seen few hack suggesting a delay in the command line, so I thought .... and what if I hold the print screen for a bit longer.
Here it goes ... on linux mint 18.3 this seems enough to activate the arrow cursor to grab your area.

**Comment by grants** [comment]
The print screen key always bind to "Print Whole Screen", I even can't find where to change it... Anyone give me some hints, thx.

**Comment by augnustin** [comment]
You need to edit your shortcuts in your preferences.

**Comment by s3r6** [comment]
1. Tired of default `shift-printscreen` behaviour with `mate-screenshot --area --interactive` popup. Developers please take a look at Xfce's screenhot app which simply starts with selecting area after `shift-printscreen`
![default](https://user-images.githubusercontent.com/4716175/50041646-825dca80-0071-11e9-9f0e-64911844680f.png)
2. I can see no mapping for `shift-printscreen` in settings but it works by default!
They are shown in CCSM but still work when disabled!
![default](https://user-images.githubusercontent.com/4716175/50041702-74f51000-0072-11e9-9a66-4ecb378a4b3b.png)

Any comments?

**Comment by s3r6** [comment]
Flameshot seems to be good alternative for taking area screenshots. Available in the repo. I did `sudo apt install flameshot dconf`. Then I replaced `/org/mate/marco/keybinding-commands/command-2` value with `flameshot gui` in dconf.

**Comment by jeffmcneill** [comment]
No need for an extra file, just add a custom shortcut in keyboard shortcuts, found in control center:

`/bin/sh -c 'sleep .1;mate-screenshot -a'`

**Comment by N0rbert** [comment]
Still happens on MATE 1.26 in Ubuntu MATE 21.10. Downstream bug report is at https://pad.lv/1615748 for 5 years (OMG!).
Fix is possible by adding sleep 0.1 as was [suggested above](https://github.com/mate-desktop/mate-utils/issues/37#issuecomment-580071673):

```
cat <<EOF | dconf load /
[org/mate/desktop/keybindings/custom0]
action="/bin/sh -c 'sleep .1;mate-screenshot -a'"
binding='<Shift><Mod4>Print'
name='MATE Screenshot of area non-interactively'
EOF
```

Hope this bug will not happen in Ubuntu MATE 22.04 LTS.

**Comment by kkonevets** [comment]
> No need for an extra file, just add a custom shortcut in keyboard shortcuts, found in control center:
> 
> `/bin/sh -c 'sleep .1;mate-screenshot -a'`

@jeffmcneill  That's the best solution, thanks!

**Comment by coldReactive** [comment]
Still exists to this day, and using the sleep method does nothing:

https://github.com/mate-desktop/mate-utils/assets/1313673/e90bc593-4428-4fc1-80b2-e24e32b1060d
